CREATE TABLE IF NOT EXISTS "UserProfile" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT,
  "tonePreference" TEXT NOT NULL DEFAULT 'friendly',
  "mood" TEXT NOT NULL DEFAULT 'curious',
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
